# PyInstaller spec for mavica-tools
# Build with: pyinstaller mavica.spec

import sys
from pathlib import Path

block_cipher = None

a = Analysis(
    ['mavica_tools/__main__.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'mavica_tools.cli',
        'mavica_tools.multipass',
        'mavica_tools.carve',
        'mavica_tools.check',
        'mavica_tools.repair',
        'mavica_tools.swaptest',
        'mavica_tools.fat12',
        'mavica_tools.recover',
        'mavica_tools.format',
        'mavica_tools.stamp',
        'mavica_tools.detect',
        'mavica_tools.history',
        'mavica_tools.report',
        'mavica_tools.export',
        'mavica_tools.gps',
        'mavica_tools.importcmd',
        'mavica_tools.fun',
        'mavica_tools.utils',
        'mavica_tools.terminal_image',
        'mavica_tools.tui',
        'mavica_tools.tui.app',
        'mavica_tools.tui.screens',
        'mavica_tools.tui.screens.home',
        'mavica_tools.tui.screens.import_workflow',
        'mavica_tools.tui.screens.recovery_workflow',
        'mavica_tools.tui.screens.multipass',
        'mavica_tools.tui.screens.carve',
        'mavica_tools.tui.screens.check',
        'mavica_tools.tui.screens.repair',
        'mavica_tools.tui.screens.swaptest',
        'mavica_tools.tui.screens.fat12_screen',
        'mavica_tools.tui.screens.recover_screen',
        'mavica_tools.tui.screens.stamp_screen',
        'mavica_tools.tui.screens.format_screen',
        'mavica_tools.tui.screens.export_screen',
        'mavica_tools.tui.screens.gps_screen',
        'mavica_tools.tui.screens.troubleshoot',
        'mavica_tools.tui.widgets',
        'mavica_tools.tui.widgets.defrag_map',
        'mavica_tools.tui.widgets.image_preview',
        'mavica_tools.tui.widgets.file_picker',
        'mavica_tools.tui.widgets.sector_map',
        'textual',
        'PIL',
        'piexif',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='mavica',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
