"""Tests for the multi-pass floppy disk imager."""

import os
import tempfile

import pytest

from mavica_tools.multipass import (
    DISK_SIZE,
    SECTOR_SIZE,
    TOTAL_SECTORS,
    merge_passes,
    read_image_file,
    sector_is_blank,
)


@pytest.fixture
def tmp_dir():
    with tempfile.TemporaryDirectory() as d:
        yield d


def make_disk_image(tmp_dir, name, sector_data_fn):
    """Create a fake disk image where each sector is generated by sector_data_fn(sector_idx)."""
    path = os.path.join(tmp_dir, name)
    with open(path, "wb") as f:
        for i in range(TOTAL_SECTORS):
            f.write(sector_data_fn(i))
    return path


def good_sector(idx):
    """A deterministic non-zero sector."""
    return bytes([(idx + b) % 256 for b in range(SECTOR_SIZE)])


def blank_sector(_idx):
    return b"\x00" * SECTOR_SIZE


class TestSectorIsBlank:
    def test_blank(self):
        assert sector_is_blank(b"\x00" * SECTOR_SIZE) is True

    def test_not_blank(self):
        assert sector_is_blank(b"\x01" + b"\x00" * (SECTOR_SIZE - 1)) is False

    def test_all_ff(self):
        assert sector_is_blank(b"\xff" * SECTOR_SIZE) is False


class TestReadImageFile:
    def test_full_size_image(self, tmp_dir):
        path = os.path.join(tmp_dir, "full.img")
        data = os.urandom(DISK_SIZE)
        with open(path, "wb") as f:
            f.write(data)
        result = read_image_file(path)
        assert len(result) == DISK_SIZE
        assert result == data

    def test_short_image_is_padded(self, tmp_dir):
        path = os.path.join(tmp_dir, "short.img")
        data = b"\xAB" * 1000
        with open(path, "wb") as f:
            f.write(data)
        result = read_image_file(path)
        assert len(result) == DISK_SIZE
        assert result[:1000] == data
        assert result[1000:] == b"\x00" * (DISK_SIZE - 1000)

    def test_empty_image(self, tmp_dir):
        path = os.path.join(tmp_dir, "empty.img")
        with open(path, "wb") as f:
            pass
        result = read_image_file(path)
        assert len(result) == DISK_SIZE
        assert result == b"\x00" * DISK_SIZE


class TestMergePasses:
    def test_all_good_passes_agree(self, tmp_dir):
        """Three identical good passes should produce all 'good' sectors."""
        paths = [
            make_disk_image(tmp_dir, f"pass{i}.img", good_sector)
            for i in range(3)
        ]
        merged, status = merge_passes(paths)
        assert len(merged) == DISK_SIZE
        assert all(s == "good" for s in status)
        # Merged data should match the original
        assert merged[:SECTOR_SIZE] == good_sector(0)
        assert merged[SECTOR_SIZE : 2 * SECTOR_SIZE] == good_sector(1)

    def test_all_blank_produces_blank_status(self, tmp_dir):
        """All-zero passes should produce 'blank' sectors."""
        paths = [
            make_disk_image(tmp_dir, f"pass{i}.img", blank_sector)
            for i in range(3)
        ]
        merged, status = merge_passes(paths)
        assert all(s == "blank" for s in status)
        assert merged == b"\x00" * DISK_SIZE

    def test_one_good_pass_recovers(self, tmp_dir):
        """If only one of three passes has data, sectors are 'recovered'."""
        paths = [
            make_disk_image(tmp_dir, "blank1.img", blank_sector),
            make_disk_image(tmp_dir, "good.img", good_sector),
            make_disk_image(tmp_dir, "blank2.img", blank_sector),
        ]
        merged, status = merge_passes(paths)
        assert all(s == "recovered" for s in status)
        # Data should come from the good pass
        assert merged[:SECTOR_SIZE] == good_sector(0)

    def test_mixed_blank_and_good(self, tmp_dir):
        """Some sectors blank in one pass, good in others."""

        def pass1_sector(idx):
            # Sector 0 is blank, rest are good
            if idx == 0:
                return blank_sector(idx)
            return good_sector(idx)

        def pass2_sector(idx):
            # All good
            return good_sector(idx)

        paths = [
            make_disk_image(tmp_dir, "pass1.img", pass1_sector),
            make_disk_image(tmp_dir, "pass2.img", pass2_sector),
        ]
        merged, status = merge_passes(paths)
        # Sector 0: one blank + one good = recovered
        assert status[0] == "recovered"
        # All other sectors: both agree = good
        assert all(s == "good" for s in status[1:])
        # Data should be correct everywhere
        assert merged[:SECTOR_SIZE] == good_sector(0)
        assert merged[SECTOR_SIZE : 2 * SECTOR_SIZE] == good_sector(1)

    def test_conflict_picks_majority(self, tmp_dir):
        """When passes disagree, majority wins."""
        sector_a = bytes([0xAA] * SECTOR_SIZE)
        sector_b = bytes([0xBB] * SECTOR_SIZE)

        # 2 passes with sector_a, 1 pass with sector_b
        paths = [
            make_disk_image(tmp_dir, "a1.img", lambda _: sector_a),
            make_disk_image(tmp_dir, "b.img", lambda _: sector_b),
            make_disk_image(tmp_dir, "a2.img", lambda _: sector_a),
        ]
        merged, status = merge_passes(paths)
        assert all(s == "conflict" for s in status)
        # Majority (sector_a) should win
        assert merged[:SECTOR_SIZE] == sector_a

    def test_single_pass(self, tmp_dir):
        """A single pass should produce all 'recovered' (one non-blank read each)."""
        paths = [make_disk_image(tmp_dir, "only.img", good_sector)]
        merged, status = merge_passes(paths)
        assert all(s == "recovered" for s in status)
        assert merged[:SECTOR_SIZE] == good_sector(0)

    def test_sector_count_matches(self, tmp_dir):
        """Status list should have exactly TOTAL_SECTORS entries."""
        paths = [make_disk_image(tmp_dir, "p.img", good_sector)]
        _, status = merge_passes(paths)
        assert len(status) == TOTAL_SECTORS
